[build]
  base = "FrontEnd/my-recipes"   # <- subcarpeta del front
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
